spring.application.name=expub4j-services
server.port=8082

# database
spring.datasource.username=services_service
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/expub4j_services?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# jms
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=test
spring.activemq.password=test